// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvnrltgeukczpxvyubtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bnJsdGdldWtjenB4dnl1YnR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODIxNTgsImV4cCI6MjA3Mzc1ODE1OH0.O2H2KrPe5Rsa6bvFm_FwNYBlHQ1U_8yB-paA2ug_b7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});